/**
 * Daggerstack character sync module.
 *
 * Authenticates against Daggerstack's Supabase backend (their public anon key
 * is embedded in the client-side Nuxt bundle — same as what any browser sees)
 * and returns a normalized character object suitable for the GM Table.
 *
 * UUID resolution is done via data/daggerstack-uuid-map.json — a pre-built
 * mapping of Daggerstack UUIDs to SRD slug IDs, generated by
 * scripts/refresh-daggerstack-uuids.js and refreshed nightly by a cron job.
 */

import { readFile } from 'fs/promises';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { getCollection } from './srd/index.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

const SUPABASE_URL = 'https://biftneoctpqfefxgelcv.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpZnRuZW9jdHBxZmVmeGdlbGN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTkwNzAzMzAsImV4cCI6MjAzNDY0NjMzMH0.w1kyOcbuQodwHb7tncNbJaLEGPLRs3rwELcYWQH1cq0';

const MAP_PATH = join(__dirname, '..', 'data', 'daggerstack-uuid-map.json');

// ─── SRD lookup table cache ───────────────────────────────────────────────────

/** In-memory cache of { byId, classes, subclasses, ancestries, communities, armors, weapons } */
let srdLookupCache = null;

/** Invalidate the cache so the next sync call re-reads the UUID map from disk. */
export function invalidateSrdLookupCache() {
  srdLookupCache = null;
}

// ─── SRD → Daggerstack-compatible adapters ────────────────────────────────────

/**
 * Parse an evasion modifier (e.g. "+1 to Evasion", "-1 to Evasion") from a
 * feature description string. Returns the integer delta, or null if not found.
 */
function parseEvasionModifier(description) {
  if (!description) return null;
  const m = description.match(/([+-]\d+)\s+to\s+(?:your\s+)?[Ee]vasion/);
  return m ? parseInt(m[1], 10) : null;
}

function adaptClass(srd) {
  return {
    name: srd.name,
    evasion: srd.starting_evasion,
    startingHitPoints: srd.starting_hp,
    domains: srd.domains || [],
    classFeatures: (srd.class_features || []).map(f => ({ name: f.name, description: f.description })),
    hopeAbility: srd.hope_feature || null,
  };
}

function adaptSubclass(srd) {
  return {
    name: srd.name,
    foundation: {
      spellcast: srd.spellcast_trait || null,
      features: (srd.foundation_features || []).map(f => ({ name: f.name, description: f.description })),
    },
  };
}

function adaptAncestry(srd) {
  return {
    name: srd.name,
    features: (srd.features || []).map(f => {
      const evasionMod = parseEvasionModifier(f.description);
      return {
        id: f.id,
        name: f.name,
        description: f.description,
        ...(evasionMod !== null ? { modify: { evasion: evasionMod } } : {}),
      };
    }),
  };
}

function adaptCommunity(srd) {
  return {
    name: srd.name,
    features: (srd.features || []).map(f => ({ name: f.name, description: f.description })),
  };
}

function adaptArmor(srd) {
  const parts = (srd.base_thresholds || '').split('/').map(s => parseInt(s.trim(), 10));
  const firstFeature = srd.features?.[0];
  const evasionMod = parseEvasionModifier(firstFeature?.description);
  return {
    name: srd.name,
    score: srd.base_score,
    majorThreshold: parts[0] || 0,
    severeThreshold: parts[1] || 0,
    tier: srd.tier,
    feature: firstFeature ? {
      name: firstFeature.name,
      description: firstFeature.description,
      ...(evasionMod !== null ? { modify: { evasion: evasionMod } } : {}),
    } : null,
  };
}

function adaptWeapon(srd) {
  const firstFeature = srd.features?.[0];
  return {
    name: srd.name,
    trait: srd.trait,
    range: srd.range,
    damage: srd.damage,
    damageType: srd.physical_or_magical,
    burden: srd.burden,
    feature: firstFeature ? { name: firstFeature.name, description: firstFeature.description } : null,
  };
}

// ─── SRD lookup table loader ──────────────────────────────────────────────────

/**
 * Load the UUID map + SRD collections and build a byId lookup table.
 * Caches the result in memory; call invalidateSrdLookupCache() to force a reload.
 */
async function loadSrdLookupTables() {
  if (srdLookupCache) return srdLookupCache;

  // Read the UUID → SRD slug mapping written by scripts/refresh-daggerstack-uuids.js
  let uuidMap = {};
  try {
    const raw = await readFile(MAP_PATH, 'utf8');
    uuidMap = JSON.parse(raw);
  } catch (err) {
    console.warn('[daggerstack-sync] Could not load UUID map (run npm run refresh:daggerstack):', err.message);
  }

  // Load all relevant SRD collections (already cached in memory by srd/parser.js)
  const [classes, subclasses, ancestries, communities, armor, weapons] = await Promise.all([
    getCollection('classes'),
    getCollection('subclasses'),
    getCollection('ancestries'),
    getCollection('communities'),
    getCollection('armor'),
    getCollection('weapons'),
  ]);

  // Build adapted item maps keyed by SRD slug ID
  const ADAPTERS = {
    classes:     { items: classes,     adapt: adaptClass     },
    subclasses:  { items: subclasses,  adapt: adaptSubclass  },
    ancestries:  { items: ancestries,  adapt: adaptAncestry  },
    communities: { items: communities, adapt: adaptCommunity },
    armor:       { items: armor,       adapt: adaptArmor     },
    weapons:     { items: weapons,     adapt: adaptWeapon    },
  };

  const bySrdId = {};
  for (const [collection, { items, adapt }] of Object.entries(ADAPTERS)) {
    for (const item of (items || [])) {
      bySrdId[item.id] = adapt(item);
    }
  }

  // Build byId: Daggerstack UUID → adapted SRD item
  const byId = {};
  for (const [uuid, entry] of Object.entries(uuidMap)) {
    const item = bySrdId[entry.srdId];
    if (item) {
      byId[uuid] = item;
    } else {
      console.warn(`[daggerstack-sync] SRD item not found for UUID ${uuid}: ${entry.collection}/${entry.srdId}`);
    }
  }

  const tables = {
    byId,
    classes:     (classes     || []).map(adaptClass),
    subclasses:  (subclasses  || []).map(adaptSubclass),
    ancestries:  (ancestries  || []).map(adaptAncestry),
    communities: (communities || []).map(adaptCommunity),
    armors:      (armor       || []).map(adaptArmor),
    weapons:     (weapons     || []).map(adaptWeapon),
  };

  srdLookupCache = tables;
  return tables;
}

// ─── Stat derivation ─────────────────────────────────────────────────────────

function deriveEvasion(classData, armorData, ancestryFeatures) {
  let evasion = classData?.evasion ?? 10;
  if (armorData?.feature?.modify?.evasion) evasion += armorData.feature.modify.evasion;
  for (const feature of (ancestryFeatures || [])) {
    if (feature?.modify?.evasion) evasion += feature.modify.evasion;
  }
  return evasion;
}

function deriveTier(level) {
  if (level >= 9) return 4;
  if (level >= 5) return 3;
  if (level >= 2) return 2;
  return 1;
}

// ─── Main sync function ───────────────────────────────────────────────────────

/**
 * Sync a character from Daggerstack.
 *
 * @param {string} url    - e.g. "https://daggerstack.com/character/17846"
 * @param {string} email  - Daggerstack account email
 * @param {string} password - Daggerstack account password
 * @returns {object}        Normalized character object for GM Table
 */
export async function syncDaggerstackCharacter(url, email, password) {
  // Extract character ID from URL
  const idMatch = url.match(/\/character\/(\d+)/);
  if (!idMatch) throw new Error('Invalid Daggerstack character URL. Expected format: https://daggerstack.com/character/{id}');
  const characterId = parseInt(idMatch[1]);

  // Authenticate
  const authResp = await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'apikey': SUPABASE_KEY },
    body: JSON.stringify({ email, password }),
  });
  const authData = await authResp.json();
  if (authData.error || !authData.access_token) {
    throw new Error(`Daggerstack login failed: ${authData.error_description || authData.error || 'unknown error'}`);
  }
  const token = authData.access_token;
  const headers = { 'apikey': SUPABASE_KEY, 'Authorization': `Bearer ${token}` };

  // Fetch character row
  const charResp = await fetch(`${SUPABASE_URL}/rest/v1/characters?id=eq.${characterId}&select=*`, { headers });
  if (!charResp.ok) throw new Error(`Failed to fetch character: HTTP ${charResp.status}`);
  const chars = await charResp.json();
  if (!chars.length) throw new Error(`Character ${characterId} not found or not accessible`);
  const raw = chars[0];

  // Load lookup tables from SRD (cached)
  let tables;
  try {
    tables = await loadSrdLookupTables();
  } catch (err) {
    console.warn('[daggerstack-sync] Could not load lookup tables:', err.message);
    tables = { byId: {}, classes: [], subclasses: [], ancestries: [], communities: [], armors: [], weapons: [] };
  }

  const resolve = (id) => (id ? tables.byId[id] : null);

  // Resolve UUIDs
  const classData = resolve(raw.baseClass);
  const subclassId = Array.isArray(raw.subclass) ? raw.subclass[0] : raw.subclass;
  const subclassData = resolve(subclassId);
  const ancestryIds = Array.isArray(raw.ancestry) ? raw.ancestry.filter(Boolean) : [raw.ancestry].filter(Boolean);
  const ancestryItems = ancestryIds.map(id => resolve(id)).filter(Boolean);
  const communityData = resolve(raw.community);

  // Resolve armor
  const armorItemId = raw.inventory?.armor?.itemId;
  const armorData = resolve(armorItemId) || null;

  // Resolve weapons
  const weapons = (raw.inventory?.weapons || []).map(w => {
    const wData = resolve(w.itemId);
    return wData ? {
      name: wData.name,
      trait: wData.trait,
      range: wData.range,
      damage: wData.damage,
      damageType: wData.damageType,
      burden: wData.burden,
      feature: wData.feature || null,
    } : { name: w.name };
  });

  // Ancestry features (for evasion modifier)
  const ancestryFeatures = ancestryItems.flatMap(a => a.features || []);

  // Compute derived stats
  const evasion = deriveEvasion(classData, armorData, ancestryFeatures);
  const tier = deriveTier(raw.level ?? 1);

  const maxHp = classData?.startingHitPoints ?? 6;
  const maxStress = 6; // global constant in Daggerstack
  const maxHope = 6;   // global constant in Daggerstack (startingHopeSlots)

  // Resources
  const resources = raw.resources || {};
  const currentHp = maxHp - (resources.health ?? 0);   // resources.health = HP marked
  const currentStress = resources.stress ?? 0;
  const hope = resources.hope ?? maxHope;
  const currentArmor = resources.armor ?? 0;
  const maxArmor = armorData?.score ?? 0;

  // Inventory
  const gold = raw.inventory?.gold ?? 0;
  const inventoryItems = (raw.inventory?.items || []).map(i => ({ name: i.name, quantity: i.quantity ?? 1 }));

  // All features
  const classFeatures = classData ? (classData.classFeatures || []).map(f => ({
    name: f.name,
    description: f.description,
    source: classData.name,
    sourceType: 'class',
  })) : [];

  const subclassFeatures = [];
  if (subclassData?.foundation?.features) {
    for (const f of subclassData.foundation.features) {
      subclassFeatures.push({ name: f.name, description: f.description, source: subclassData.name, sourceType: 'subclass', charge: f.charge });
    }
  }

  const ancestryFeaturesNormalized = ancestryFeatures.map(f => ({
    name: f.name,
    description: f.description,
    source: ancestryItems.find(a => a.features?.some(af => af.id === f.id))?.name || 'Ancestry',
    sourceType: 'ancestry',
  }));

  const communityFeatureNormalized = communityData?.features?.map(f => ({
    name: f.name,
    description: f.description,
    source: communityData.name,
    sourceType: 'community',
  })) || [];

  const _debug = {
    supabaseRow: raw,
    resolved: {
      class: classData || null,
      subclass: subclassData || null,
      ancestries: ancestryItems,
      community: communityData || null,
      armor: armorData,
      weapons: (raw.inventory?.weapons || []).map(w => ({ slot: w, resolved: resolve(w.itemId) || null })),
    },
  };

  const _lookupTables = {
    classes:     tables.classes     || [],
    subclasses:  tables.subclasses  || [],
    ancestries:  tables.ancestries  || [],
    communities: tables.communities || [],
    armors:      tables.armors      || [],
    weapons:     tables.weapons     || [],
  };

  return { _debug, _lookupTables, character: {
    // Daggerstack link
    daggerstackUrl: url,
    daggerstackEmail: email,
    daggerstackPassword: password,
    daggerstackCharacterId: characterId,

    // Identity
    name: raw.name,
    pronouns: raw.pronouns || '',
    description: raw.description || '',
    level: raw.level ?? 1,

    // Class info
    class: classData?.name || null,
    subclass: subclassData?.name || null,
    domains: classData?.domains || [],
    spellcastTrait: subclassData?.foundation?.spellcast || null,
    hopeAbility: classData?.hopeAbility || null,
    hopeAbilityName: classData?.hopeAbility?.name || null,

    // Ancestry & community
    ancestry: ancestryItems.map(a => a.name),
    community: communityData?.name || null,

    // Traits
    traits: {
      agility:   raw.agility?.score ?? 0,
      strength:  raw.strength?.score ?? 0,
      finesse:   raw.finesse?.score ?? 0,
      instinct:  raw.instinct?.score ?? 0,
      presence:  raw.presence?.score ?? 0,
      knowledge: raw.knowledge?.score ?? 0,
    },

    // Tier (derived from level)
    tier,

    // Defense
    evasion,
    armorScore: armorData?.score ?? 0,
    armorName: armorData?.name || (raw.inventory?.armor?.name) || null,
    armorThresholds: armorData ? { major: armorData.majorThreshold, severe: armorData.severeThreshold } : null,

    // Resources (current state)
    maxHp,
    currentHp,
    maxStress,
    currentStress,
    maxHope,
    hope,
    maxArmor,
    currentArmor,

    // Equipment
    weapons,
    gold,
    inventory: inventoryItems,

    // Features
    classFeatures,
    subclassFeatures,
    ancestryFeatures: ancestryFeaturesNormalized,
    communityFeatures: communityFeatureNormalized,

    // Experiences
    experiences: (raw.experience || []).map(e => ({ name: e.name, score: e.score })),

    // Companion (if any)
    companion: raw.companion?.name ? {
      name: raw.companion.name,
      species: raw.companion.species,
      evasion: raw.companion.evasion ?? 10,
      maxStress: raw.companion.stress?.slots ?? 3,
      currentStress: raw.companion.stress?.current ?? 0,
    } : null,

    // Carry-over runtime fields (blank by default, populated from existing element on re-sync)
    conditions: '',
    playerName: '',
    elementType: 'character',
  } };
}
