/**
 * AUTO-GENERATED by scripts/generate-beastform-srd-data.mjs — do not edit by hand.
 * Source: daggerheart-srd/.build/03_json/beastforms.json
 * Regenerate: `node scripts/generate-beastform-srd-data.mjs`
 */
export const BEASTFORM_ITEMS = [
  {
    "id": "srd-bst-agile-scout",
    "name": "Agile Scout",
    "tier": 1,
    "examples": "(Fox, Mouse, Weasel, etc.)",
    "trait_bonus": "Agility +1",
    "evasion_bonus": "Evasion +2",
    "attack": "Melee Agility d4 phy",
    "advantages": "deceive, locate, sneak",
    "features": [
      {
        "id": "srd-bst-agile-scout-feat-agile",
        "name": "Agile",
        "type": "passive",
        "description": "Your movement is silent, and you can **spend a Hope** to move up to Far range without rolling."
      },
      {
        "id": "srd-bst-agile-scout-feat-fragile",
        "name": "Fragile",
        "type": "passive",
        "description": "When you take Major or greater damage, you drop out of Beastform."
      }
    ]
  },
  {
    "id": "srd-bst-household-friend",
    "name": "Household Friend",
    "tier": 1,
    "examples": "(Cat, Dog, Rabbit, etc.)",
    "trait_bonus": "Instinct +1",
    "evasion_bonus": "Evasion +2",
    "attack": "Melee Instinct d6 phy",
    "advantages": "climb, locate, protect",
    "features": [
      {
        "id": "srd-bst-household-friend-feat-companion",
        "name": "Companion",
        "type": "passive",
        "description": "When you Help an Ally, you can roll a **d8** as your advantage die."
      },
      {
        "id": "srd-bst-household-friend-feat-fragile",
        "name": "Fragile",
        "type": "passive",
        "description": "When you take Major or greater damage, you drop out of Beastform."
      }
    ]
  },
  {
    "id": "srd-bst-nimble-grazer",
    "name": "Nimble Grazer",
    "tier": 1,
    "examples": "(Deer, Gazelle, Goat, etc.)",
    "trait_bonus": "Agility +1",
    "evasion_bonus": "Evasion +3",
    "attack": "Melee Agility d6 phy",
    "advantages": "leap, sneak, sprint",
    "features": [
      {
        "id": "srd-bst-nimble-grazer-feat-elusive-prey",
        "name": "Elusive Prey",
        "type": "passive",
        "description": "When an attack roll against you would succeed, you can **mark a Stress** and roll a **d4.** Add the result to your Evasion against this attack."
      },
      {
        "id": "srd-bst-nimble-grazer-feat-fragile",
        "name": "Fragile",
        "type": "passive",
        "description": "When you take Major or greater damage, you drop out of Beastform."
      }
    ]
  },
  {
    "id": "srd-bst-pack-predator",
    "name": "Pack Predator",
    "tier": 1,
    "examples": "(Coyote, Hyena, Wolf, etc.)",
    "trait_bonus": "Strength +2",
    "evasion_bonus": "Evasion +1",
    "attack": "Melee Strength d8+2 phy",
    "advantages": "attack, sprint, track",
    "features": [
      {
        "id": "srd-bst-pack-predator-feat-hobbling-strike",
        "name": "Hobbling Strike",
        "type": "passive",
        "description": "When you succeed on an attack against a target within Melee range, you can **mark a Stress** to make the target temporarily _Vulnerable_."
      },
      {
        "id": "srd-bst-pack-predator-feat-pack-hunting",
        "name": "Pack Hunting",
        "type": "passive",
        "description": "When you succeed on an attack against the same target as an ally who acts immediately before you, add a **d8** to your damage roll."
      }
    ]
  },
  {
    "id": "srd-bst-aquatic-scout",
    "name": "Aquatic Scout",
    "tier": 1,
    "examples": "(Eel, Fish, Octopus, etc.)",
    "trait_bonus": "Agility +1",
    "evasion_bonus": "Evasion +2",
    "attack": "Melee Agility d4 phy",
    "advantages": "navigate, sneak, swim",
    "features": [
      {
        "id": "srd-bst-aquatic-scout-feat-aquatic",
        "name": "Aquatic",
        "type": "passive",
        "description": "You can breathe and move naturally underwater."
      },
      {
        "id": "srd-bst-aquatic-scout-feat-fragile",
        "name": "Fragile",
        "type": "passive",
        "description": "When you take Major or greater damage, you drop out of Beastform."
      }
    ]
  },
  {
    "id": "srd-bst-stalking-arachnid",
    "name": "Stalking Arachnid",
    "tier": 1,
    "examples": "(Tarantula, Wolf Spider, etc.)",
    "trait_bonus": "Finesse +1",
    "evasion_bonus": "Evasion +2",
    "attack": "Melee Finesse d6+1 phy",
    "advantages": "attack, climb, sneak",
    "features": [
      {
        "id": "srd-bst-stalking-arachnid-feat-venomous-bite",
        "name": "Venomous Bite",
        "type": "passive",
        "description": "When you succeed on an attack against a target within Melee range, the target becomes temporarily _Poisoned_. A _Poisoned_ creature takes **1d10** direct physical damage each time they act."
      },
      {
        "id": "srd-bst-stalking-arachnid-feat-webslinger",
        "name": "Webslinger",
        "type": "passive",
        "description": "You can create a strong web material useful for both adventuring and battle. The web is resilient enough to support one creature. You can temporarily _Restrain_ a target within Close range by succeeding on a Finesse Roll against them."
      }
    ]
  },
  {
    "id": "srd-bst-armored-sentry",
    "name": "Armored Sentry",
    "tier": 2,
    "examples": "(Armadillo, Pangolin, Turtle, etc.)",
    "trait_bonus": "Strength +1",
    "evasion_bonus": "Evasion +1",
    "attack": "Melee Strength d8+2 phy",
    "advantages": "dig, locate, protect",
    "features": [
      {
        "id": "srd-bst-armored-sentry-feat-armored-shell",
        "name": "Armored Shell",
        "type": "passive",
        "description": "Your hardened exterior gives you resistance to physical damage. Additionally, **mark an Armor Slot** to retract into your shell. While in your shell, physical damage is reduced by a number equal to your Armor Score (after applying resistance), but you can't perform other actions without leaving this form."
      },
      {
        "id": "srd-bst-armored-sentry-feat-cannonball",
        "name": "Cannonball",
        "type": "passive",
        "description": "**Mark a Stress** to allow an ally to throw or launch you at an adversary. To do so, the ally makes an attack roll using Agility or Strength (their choice) against a target within Close range. On a success, the adversary takes **d12+2** physical damage using the thrower's Proficiency. You can **spend a Hope** to target an additional adversary within Very Close range of the first. The second target takes half the damage dealt to the first target."
      }
    ]
  },
  {
    "id": "srd-bst-powerful-beast",
    "name": "Powerful Beast",
    "tier": 2,
    "examples": "(Bear, Bull, Moose, etc.)",
    "trait_bonus": "Strength +3",
    "evasion_bonus": "Evasion +1",
    "attack": "Melee Strength d10+4 phy",
    "advantages": "navigate, protect, scare",
    "features": [
      {
        "id": "srd-bst-powerful-beast-feat-rampage",
        "name": "Rampage",
        "type": "passive",
        "description": "When you roll a 1 on a damage die, you can roll a **d10** and add the result to the damage roll. Additionally, before you make an attack roll, you can **mark a Stress** to gain a +1 bonus to your Proficiency for that attack."
      },
      {
        "id": "srd-bst-powerful-beast-feat-thick-hide",
        "name": "Thick Hide",
        "type": "passive",
        "description": "You gain a +2 bonus to your damage thresholds."
      }
    ]
  },
  {
    "id": "srd-bst-mighty-strider",
    "name": "Mighty Strider",
    "tier": 2,
    "examples": "(Camel, Horse, Zebra, etc.)",
    "trait_bonus": "Agility +1",
    "evasion_bonus": "Evasion +2",
    "attack": "Melee Agility d8+1 phy",
    "advantages": "leap, navigate, sprint",
    "features": [
      {
        "id": "srd-bst-mighty-strider-feat-carrier",
        "name": "Carrier",
        "type": "passive",
        "description": "You can carry up to two willing allies with you when you move."
      },
      {
        "id": "srd-bst-mighty-strider-feat-trample",
        "name": "Trample",
        "type": "passive",
        "description": "**Mark a Stress** to move up to Close range in a straight line and make an attack against all targets within Melee range of the line. Targets you succeed against take **d8+1** physical damage using your Proficiency and are temporarily _Vulnerable_."
      }
    ]
  },
  {
    "id": "srd-bst-striking-serpent",
    "name": "Striking Serpent",
    "tier": 2,
    "examples": "(Cobra, Rattlesnake, Viper, etc.)",
    "trait_bonus": "Finesse +1",
    "evasion_bonus": "Evasion +2",
    "attack": "Very Close Finesse d8+4 phy",
    "advantages": "climb, deceive, sprint",
    "features": [
      {
        "id": "srd-bst-striking-serpent-feat-venomous-strike",
        "name": "Venomous Strike",
        "type": "passive",
        "description": "Make an attack against any number of targets within Very Close range. On a success, a target is temporarily _Poisoned_. A _Poisoned_ creature takes **1d10** direct physical damage each time they act."
      },
      {
        "id": "srd-bst-striking-serpent-feat-warning-hiss",
        "name": "Warning Hiss",
        "type": "passive",
        "description": "**Mark a Stress** to force any number of targets within Melee range to move back to Very Close range."
      }
    ]
  },
  {
    "id": "srd-bst-pouncing-predator",
    "name": "Pouncing Predator",
    "tier": 2,
    "examples": "(Cheetah, Lion, Panther, etc.)",
    "trait_bonus": "Instinct +1",
    "evasion_bonus": "Evasion +3",
    "attack": "Melee Instinct d8+6 phy",
    "advantages": "attack, climb, sneak",
    "features": [
      {
        "id": "srd-bst-pouncing-predator-feat-fleet",
        "name": "Fleet",
        "type": "passive",
        "description": "**Spend a Hope** to move up to Far range without rolling."
      },
      {
        "id": "srd-bst-pouncing-predator-feat-takedown",
        "name": "Takedown",
        "type": "passive",
        "description": "**Mark a Stress** to move into Melee range of a target and make an attack roll against them. On a success, you gain a +2 bonus to your Proficiency for this attack and the target must mark a Stress."
      }
    ]
  },
  {
    "id": "srd-bst-winged-beast",
    "name": "Winged Beast",
    "tier": 2,
    "examples": "(Hawk, Owl, Raven, etc.)",
    "trait_bonus": "Finesse +1",
    "evasion_bonus": "Evasion +3",
    "attack": "Melee Finesse d4+2 phy",
    "advantages": "deceive, locate, scare",
    "features": [
      {
        "id": "srd-bst-winged-beast-feat-bird-s-eye-view",
        "name": "Bird's-Eye View",
        "type": "passive",
        "description": "You can fly at will. Once per rest while you are airborne, you can ask the GM a question about the scene below you without needing to roll. The first time a character makes a roll to act on this information, they gain advantage on the roll."
      },
      {
        "id": "srd-bst-winged-beast-feat-hollow-bones",
        "name": "Hollow Bones",
        "type": "passive",
        "description": "You gain a -2 penalty to your damage thresholds."
      }
    ]
  },
  {
    "id": "srd-bst-great-predator",
    "name": "Great Predator",
    "tier": 3,
    "examples": "(Dire Wolf, Velociraptor, Sabertooth Tiger, etc.)",
    "trait_bonus": "Strength +2",
    "evasion_bonus": "Evasion +2",
    "attack": "Melee Strength d12+8 phy",
    "advantages": "attack, sneak, sprint",
    "features": [
      {
        "id": "srd-bst-great-predator-feat-carrier",
        "name": "Carrier",
        "type": "passive",
        "description": "You can carry up to two willing allies with you when you move."
      },
      {
        "id": "srd-bst-great-predator-feat-vicious-maul",
        "name": "Vicious Maul",
        "type": "passive",
        "description": "When you succeed on an attack against a target, you can **spend a Hope** to make them temporarily _Vulnerable_ and gain a +1 bonus to your Proficiency for this attack."
      }
    ]
  },
  {
    "id": "srd-bst-mighty-lizard",
    "name": "Mighty Lizard",
    "tier": 3,
    "examples": "(Alligator, Crocodile, Gila Monster, etc.)",
    "trait_bonus": "Instinct +2",
    "evasion_bonus": "Evasion +1",
    "attack": "Melee Instinct d10+7 phy",
    "advantages": "attack, sneak, track",
    "features": [
      {
        "id": "srd-bst-mighty-lizard-feat-physical-defense",
        "name": "Physical Defense",
        "type": "passive",
        "description": "You gain a +3 bonus to your damage thresholds."
      },
      {
        "id": "srd-bst-mighty-lizard-feat-snapping-strike",
        "name": "Snapping Strike",
        "type": "passive",
        "description": "When you succeed on an attack against a target within Melee range, you can **spend a Hope** to clamp that opponent in your jaws, making them temporarily _Restrained_ and _Vulnerable._"
      }
    ]
  },
  {
    "id": "srd-bst-great-winged-beast",
    "name": "Great Winged Beast",
    "tier": 3,
    "examples": "(Giant Eagle, Falcon, etc.)",
    "trait_bonus": "Finesse +2",
    "evasion_bonus": "Evasion +3",
    "attack": "Melee Finesse d8+6 phy",
    "advantages": "deceive, distract, locate",
    "features": [
      {
        "id": "srd-bst-great-winged-beast-feat-bird-s-eye-view",
        "name": "Bird's-Eye View",
        "type": "passive",
        "description": "You can fly at will. Once per rest while you are airborne, you can ask the GM a question about the scene below you without needing to roll. The first time a character makes a roll to act on this information, they gain advantage on the roll."
      },
      {
        "id": "srd-bst-great-winged-beast-feat-carrier",
        "name": "Carrier",
        "type": "passive",
        "description": "You can carry up to two willing allies with you when you move."
      }
    ]
  },
  {
    "id": "srd-bst-aquatic-predator",
    "name": "Aquatic Predator",
    "tier": 3,
    "examples": "(Dolphin, Orca, Shark, etc.)",
    "trait_bonus": "Agility +2",
    "evasion_bonus": "Evasion +4",
    "attack": "Melee Agility d10+6 phy",
    "advantages": "attack, swim, track",
    "features": [
      {
        "id": "srd-bst-aquatic-predator-feat-aquatic",
        "name": "Aquatic",
        "type": "passive",
        "description": "You can breathe and move naturally underwater."
      },
      {
        "id": "srd-bst-aquatic-predator-feat-vicious-maul",
        "name": "Vicious Maul",
        "type": "passive",
        "description": "When you succeed on an attack against a target, you can **spend a Hope** to make them _Vulnerable_ and gain a +1 bonus to your Proficiency for this attack."
      }
    ]
  },
  {
    "id": "srd-bst-legendary-beast",
    "name": "Legendary Beast",
    "tier": 3,
    "examples": "(Upgraded Tier 1 Options)",
    "trait_bonus": "",
    "evasion_bonus": "",
    "attack": "",
    "advantages": "",
    "features": [
      {
        "id": "srd-bst-legendary-beast-feat-evolved",
        "name": "Evolved",
        "type": "passive",
        "description": "Pick a Tier 1 Beastform option and become a larger, more powerful version of that creature. While you're in this form, you retain all traits and features from the original form and gain the following bonuses:\n\n- A +6 bonus to damage rolls\n- A +1 bonus to the trait used by this form\n- A +2 bonus to Evasion"
      }
    ]
  },
  {
    "id": "srd-bst-legendary-hybrid",
    "name": "Legendary Hybrid",
    "tier": 3,
    "examples": "(Griffon, Sphinx, etc.)",
    "trait_bonus": "Strength +2",
    "evasion_bonus": "Evasion +3",
    "attack": "Melee Strength d10+8 phy",
    "advantages": "",
    "features": [
      {
        "id": "srd-bst-legendary-hybrid-feat-hybrid-features",
        "name": "Hybrid Features",
        "type": "passive",
        "description": "To transform into this creature, **mark an additional Stress.** Choose any two Beastform options from Tiers 1-2. Choose a total of four advantages and two features from those options."
      }
    ]
  },
  {
    "id": "srd-bst-massive-behemoth",
    "name": "Massive Behemoth",
    "tier": 4,
    "examples": "(Elephant, Mammoth, Rhinoceros, etc.)",
    "trait_bonus": "Strength +3",
    "evasion_bonus": "Evasion +1",
    "attack": "Melee Strength d12+12 phy",
    "advantages": "locate, protect, scare, sprint",
    "features": [
      {
        "id": "srd-bst-massive-behemoth-feat-carrier",
        "name": "Carrier",
        "type": "passive",
        "description": "You can carry up to four willing allies with you when you move."
      },
      {
        "id": "srd-bst-massive-behemoth-feat-demolish",
        "name": "Demolish",
        "type": "passive",
        "description": "**Spend a Hope** to move up to Far range in a straight line and make an attack against all targets within Melee range of the line. Targets you succeed against take **d8+10** physical damage using your Proficiency and are temporarily _Vulnerable._"
      },
      {
        "id": "srd-bst-massive-behemoth-feat-undaunted",
        "name": "Undaunted",
        "type": "passive",
        "description": "You gain a +2 bonus to all your damage thresholds."
      }
    ]
  },
  {
    "id": "srd-bst-terrible-lizard",
    "name": "Terrible Lizard",
    "tier": 4,
    "examples": "(Brachiosaurus, Tyrannosaurus, etc.)",
    "trait_bonus": "Strength +3",
    "evasion_bonus": "Evasion +2",
    "attack": "Melee Strength d12+10 phy",
    "advantages": "attack, deceive, scare, track",
    "features": [
      {
        "id": "srd-bst-terrible-lizard-feat-devastating-strikes",
        "name": "Devastating Strikes",
        "type": "passive",
        "description": "When you deal Severe damage to a target within Melee range, you can **mark a Stress** to force them to mark an additional Hit Point."
      },
      {
        "id": "srd-bst-terrible-lizard-feat-massive-stride",
        "name": "Massive Stride",
        "type": "passive",
        "description": "You can move up to Far range without rolling. You ignore rough terain (at the GM's discretion) due to your size."
      }
    ]
  },
  {
    "id": "srd-bst-mythic-aerial-hunter",
    "name": "Mythic Aerial Hunter",
    "tier": 4,
    "examples": "(Dragon, Pterodactyl, Roc, Wyvern, etc.)",
    "trait_bonus": "Finesse +3",
    "evasion_bonus": "Evasion +4",
    "attack": "Melee Finesse d10+11 phy",
    "advantages": "attack, deceive, locate, navigate",
    "features": [
      {
        "id": "srd-bst-mythic-aerial-hunter-feat-carrier",
        "name": "Carrier",
        "type": "passive",
        "description": "You can carry up to three willing allies with you when you move."
      },
      {
        "id": "srd-bst-mythic-aerial-hunter-feat-deadly-raptor",
        "name": "Deadly Raptor",
        "type": "passive",
        "description": "You can fly at will and move up to Far range as part of your action. When you move in a straight line into Melee range of a target from at least Close range and make an attack against that target in the same action, you can reroll all damage dice that rolled a result lower than your Proficiency."
      }
    ]
  },
  {
    "id": "srd-bst-epic-aquatic-beast",
    "name": "Epic Aquatic Beast",
    "tier": 4,
    "examples": "(Giant Squid, Whale, etc.)",
    "trait_bonus": "Agility +3",
    "evasion_bonus": "Evasion +3",
    "attack": "Melee Agility d10+10 phy",
    "advantages": "locate, protect, scare, track",
    "features": [
      {
        "id": "srd-bst-epic-aquatic-beast-feat-ocean-master",
        "name": "Ocean Master",
        "type": "passive",
        "description": "You can breathe and move naturally underwater. When you succeed on an attack against a target within Melee range, you can temporarily _Restrain_ them."
      },
      {
        "id": "srd-bst-epic-aquatic-beast-feat-unyielding",
        "name": "Unyielding",
        "type": "passive",
        "description": "When you would mark an Armor Slot, roll a **d6.** On a result of 5 or higher, reduce the severity by one threshold without marking an Armor Slot."
      }
    ]
  },
  {
    "id": "srd-bst-mythic-beast",
    "name": "Mythic Beast",
    "tier": 4,
    "examples": "(Upgraded Tier 1 or Tier 2 Options)",
    "trait_bonus": "",
    "evasion_bonus": "",
    "attack": "",
    "advantages": "",
    "features": [
      {
        "id": "srd-bst-mythic-beast-feat-evolved",
        "name": "Evolved",
        "type": "passive",
        "description": "Pick a Tier 1 or Tier 2 Beastform option and become a larger, more powerful version of that creature. While you're in this form, you retain all traits and features from the original form and gain the following bonuses:\n\n- A +9 bonus to damage rolls\n- A +2 bonus to the trait used by this form\n- A +3 bonus to Evasion\n- Your damage die increases by one size (d6 becomes d8, d8 becomes d10, etc.)"
      }
    ]
  },
  {
    "id": "srd-bst-mythic-hybrid",
    "name": "Mythic Hybrid",
    "tier": 4,
    "examples": "(Chimera, Cockatrice, Manticore, etc.)",
    "trait_bonus": "Strength +3",
    "evasion_bonus": "Evasion +2",
    "attack": "Strength Melee d12+10 phy",
    "advantages": "",
    "features": [
      {
        "id": "srd-bst-mythic-hybrid-feat-hybrid-features",
        "name": "Hybrid Features",
        "type": "passive",
        "description": "To transform into this creature, **mark 2 additional Stress.** Choose any three Beastform options from Tiers 1-3. Choose a total of five advantages and three features from those options."
      }
    ]
  }
];
